edit: fix gui editor editing a mail with attachments
The trace back looks like:

  undefined method `slice_by_display_length' for #<Array:0x00000003316980>
  lib/sup/buffer.rb:83:in `write'
  lib/sup/modes/scroll_mode.rb:238:in `block in draw_line_from_array'
  lib/sup/modes/scroll_mode.rb:224:in `each'
  lib/sup/modes/scroll_mode.rb:224:in `each_with_index'
  lib/sup/modes/scroll_mode.rb:224:in `draw_line_from_array'
  lib/sup/modes/scroll_mode.rb:199:in `draw_line'
  lib/sup/modes/line_cursor_mode.rb:52:in `draw_line'

Because the color label is nested:

  [[:editing_frozen_text_color, [[:attachment_color, "..."]]]]

Thanks @97-109-107 for reporting!

FossilOrigin-Name: d8edb7f5662f3d0205229c3398d2f7e68cb88d12c5e16302782a9e5b86538722